# Generated by Django 4.2.7 on 2025-09-25 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('donor_name', models.CharField(max_length=200)),
                ('donor_email', models.EmailField(max_length=254)),
                ('donor_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('donation_type', models.CharField(choices=[('one_time', 'One-time'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual')], default='one_time', max_length=20)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('payment_method', models.CharField(choices=[('stripe', 'Credit/Debit Card'), ('mpesa', 'M-Pesa'), ('bank_transfer', 'Bank Transfer'), ('paypal', 'PayPal'), ('other', 'Other')], max_length=50)),
                ('transaction_id', models.CharField(max_length=200, unique=True)),
                ('payment_reference', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('is_tax_deductible', models.BooleanField(default=True)),
                ('receipt_sent', models.BooleanField(default=False)),
                ('receipt_sent_at', models.DateTimeField(blank=True, null=True)),
                ('is_recurring', models.BooleanField(default=False)),
                ('next_payment_date', models.DateField(blank=True, null=True)),
                ('subscription_id', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Donation',
                'verbose_name_plural': 'Donations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DonationCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('goal_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('raised_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='campaigns/')),
                ('campaign_type', models.CharField(choices=[('general', 'General Fund'), ('scholarship', 'Scholarship Program'), ('workshop', 'Workshop & Mentorship'), ('community', 'Community Project'), ('emergency', 'Emergency Fund'), ('infrastructure', 'Infrastructure')], max_length=50)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_urgent', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Donation Campaign',
                'verbose_name_plural': 'Donation Campaigns',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Partnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('organization_name', models.CharField(max_length=200)),
                ('organization_type', models.CharField(choices=[('corporate', 'Corporate/Business'), ('educational', 'Educational Institution'), ('government', 'Government Agency'), ('ngo', 'NGO/Non-profit'), ('foundation', 'Foundation'), ('other', 'Other')], max_length=20)),
                ('contact_person', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('partnership_interests', models.JSONField(help_text='Array of partnership types')),
                ('proposal_details', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('active', 'Active Partnership'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Partnership',
                'verbose_name_plural': 'Partnerships',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('interests', models.JSONField(help_text='Array of interest areas')),
                ('skills_experience', models.TextField()),
                ('availability', models.CharField(choices=[('weekdays', 'Weekdays'), ('weekends', 'Weekends'), ('evenings', 'Evenings'), ('flexible', 'Flexible'), ('events', 'Events only')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('active', 'Active'), ('inactive', 'Inactive'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('hours_contributed', models.PositiveIntegerField(default=0)),
                ('projects_participated', models.PositiveIntegerField(default=0)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Volunteer',
                'verbose_name_plural': 'Volunteers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DonationImpact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('impact_description', models.TextField()),
                ('beneficiaries_count', models.PositiveIntegerField(default=0)),
                ('impact_metrics', models.JSONField(blank=True, null=True)),
                ('impact_images', models.TextField(blank=True, help_text='JSON array of image URLs', null=True)),
                ('impact_video_url', models.URLField(blank=True, null=True)),
                ('report_date', models.DateField()),
                ('report_sent', models.BooleanField(default=False)),
                ('report_sent_at', models.DateTimeField(blank=True, null=True)),
                ('donation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='impact', to='donations.donation')),
            ],
            options={
                'verbose_name': 'Donation Impact',
                'verbose_name_plural': 'Donation Impacts',
            },
        ),
        migrations.AddField(
            model_name='donation',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='donations.donationcampaign'),
        ),
    ]
