# Generated by Django 4.2.7 on 2025-10-15 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='alumni_donation_period',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('yearly', 'Yearly'), ('custom', 'Custom')], help_text='For alumni donors: monthly, yearly, or custom', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='is_alumni',
            field=models.BooleanField(default=False),
        ),
    ]
