# Generated by Django 4.2.7 on 2025-09-26 11:17

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Organization',
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
