# Generated by Django 4.2.7 on 2025-12-25 10:12

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("question", models.CharField(max_length=300)),
                ("answer", django_ckeditor_5.fields.CKEditor5Field()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("scholarships", "Scholarships"),
                            ("donations", "Donations"),
                            ("volunteering", "Volunteering"),
                            ("programs", "Programs"),
                        ],
                        max_length=50,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQs",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ImpactStatistic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("title", models.CharField(max_length=100)),
                ("value", models.CharField(max_length=20)),
                ("description", models.CharField(max_length=200)),
                (
                    "icon",
                    models.CharField(help_text="CSS class for icon", max_length=50),
                ),
                ("color", models.CharField(default="primary", max_length=20)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Impact Statistic",
                "verbose_name_plural": "Impact Statistics",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="KEEFA", max_length=200)),
                (
                    "tagline",
                    models.CharField(default="Empowering Communities", max_length=300),
                ),
                ("mission", django_ckeditor_5.fields.CKEditor5Field()),
                ("vision", django_ckeditor_5.fields.CKEditor5Field()),
                ("values", django_ckeditor_5.fields.CKEditor5Field()),
                ("story", django_ckeditor_5.fields.CKEditor5Field()),
                ("email", models.EmailField(default="info@keefa.org", max_length=254)),
                ("phone", models.CharField(default="+254 123 456 789", max_length=20)),
                (
                    "address",
                    models.TextField(default="Sheywe Hotel Area, Kakamega, Kenya"),
                ),
                ("facebook_url", models.URLField(blank=True, null=True)),
                ("twitter_url", models.URLField(blank=True, null=True)),
                ("instagram_url", models.URLField(blank=True, null=True)),
                ("linkedin_url", models.URLField(blank=True, null=True)),
                ("youtube_url", models.URLField(blank=True, null=True)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="organization/"),
                ),
                (
                    "hero_image",
                    models.ImageField(blank=True, null=True, upload_to="organization/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Organization Information",
                "verbose_name_plural": "Organization Information",
            },
        ),
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("logo", models.ImageField(upload_to="partners/")),
                ("website_url", models.URLField(blank=True, null=True)),
                (
                    "partnership_type",
                    models.CharField(
                        choices=[
                            ("corporate", "Corporate Partner"),
                            ("educational", "Educational Institution"),
                            ("government", "Government Agency"),
                            ("ngo", "NGO/Non-profit"),
                            ("foundation", "Foundation"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Partner",
                "verbose_name_plural": "Partners",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("maintenance_mode", models.BooleanField(default=False)),
                ("maintenance_message", models.TextField(blank=True, null=True)),
                (
                    "google_analytics_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "facebook_pixel_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "whatsapp_number",
                    models.CharField(default="+254123456789", max_length=20),
                ),
                (
                    "emergency_contact",
                    models.CharField(default="+254111222333", max_length=20),
                ),
                (
                    "meta_title",
                    models.CharField(
                        default="KEEFA - Empowering Communities", max_length=60
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        default="Empowering futures, building communities through scholarships and community outreach programs",
                        max_length=160,
                    ),
                ),
                (
                    "meta_keywords",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Site Settings",
                "verbose_name_plural": "Site Settings",
            },
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=100)),
                ("position", models.CharField(max_length=100)),
                ("bio", models.TextField()),
                ("photo", models.ImageField(upload_to="team/")),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("linkedin_url", models.URLField(blank=True, null=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Team Member",
                "verbose_name_plural": "Team Members",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=100)),
                ("position", models.CharField(max_length=100)),
                ("content", models.TextField()),
                ("photo", models.ImageField(upload_to="testimonials/")),
                (
                    "program_type",
                    models.CharField(
                        choices=[
                            ("scholarship", "Scholarship Program"),
                            ("workshop", "Workshop & Mentorship"),
                            ("community", "Community Project"),
                            ("general", "General"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "rating",
                    models.PositiveIntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Testimonial",
                "verbose_name_plural": "Testimonials",
                "ordering": ["order"],
            },
        ),
    ]
